name: Build and Publish Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build bootstrap
        working-directory: ./bootstrap-go
        run: ./build.sh
        env:
          CGO_ENABLED: 0

      - name: Build index.js
        working-directory: ./compute-type-value
        run: yarn install && yarn build

      - name: Prepare runtime directory
        run: |
          mkdir -p tlrt
          mkdir -p tlrt/runtime
          cp bootstrap-go/build/bootstrap tlrt/runtime/bootstrap
          cp compute-type-value/dist/index.js tlrt/runtime/index.js
          cp terraform/aws_lambda_layer.tf tlrt/aws_lambda_layer.tf

      - name: Create tar.gz and zip
        run: |
          tar -czf tlrt.tar.gz tlrt
          zip -r tlrt.zip tlrt

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: tlrt-${{ github.run_number }}
          release_name: tlrt
          draft: false
          prerelease: false

      - name: Upload tar.gz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./tlrt.tar.gz
          asset_name: tlrt.tar.gz
          asset_content_type: application/gzip

      - name: Upload zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./tlrt.zip
          asset_name: tlrt.zip
          asset_content_type: application/zip